brew_taps:
  - buo/cask-upgrade
  - genkiroid/cert
  - homebrew/cask
  - homebrew/core
  - jesseduffield/lazydocker
  - skanehira/docui

brew_cask_apps:
  - authy
  - alfred
  - slack
  - iterm2
  - firefox
  - google-chrome
  - hammerspoon
  - macdown
  - spectacle
  - vagrant
#  - virtualbox
  - visual-studio-code
  - showyedge
  - docker
  - clipy

brew_packages:
  - cert
  - git
  - glib
  - go
  - grep
  - httpie
  - jq
  - nkf
  - oniguruma
  - openssl
  - peco
  - pwgen
  - ruby
  - source-highlight
  - telnet
  - terraform
  - tig
  - tmux
  - tmux-xpanes
  - tree
  - wget
  - zsh
  - zsh-completions
  - yamllint
  - lazydocker
  - docui
  - shellcheck
  - htop
  - ccat
  - ffmpeg
  - hugo
  - git-secrets
  - nodenv
